autoInstallPeers: true

catalogMode: prefer

# change this once added missing deps
cleanupUnusedCatalogs: false

dedupePeers: true

ignoreScripts: true

ignoreWorkspaceRootCheck: true

linkWorkspacePackages: true

verifyDepsBeforeRun: install

preferWorkspacePackages: true

shamefullyHoist: true

shellEmulator: true

strictPeerDependencies: false

trustPolicy: no-downgrade

packages:
  - examples/**
  - packages/**

overrides:
  '@types/node': 'catalog:types'
  chokidar: ^5.0.0
  rolldown: 'catalog:utils'
  devframe: 'catalog:inspector'
  sharp: ^0.35.5
  semver: ^7.8.5
  vue: 3.5.43
  why-is-node-running: 'catalog:utils'

allowBuilds:
  '@parcel/watcher': false
  '@sentry/cli': true
  core-js: false
  esbuild: false
  sharp: true
  unrs-resolver: false
  vue-demi: false

catalogs:
  build:
    tsdown: ^0.23.0
  eslint:
    '@antfu/eslint-config': ^9.5.1
    eslint: ^10.12.0
    eslint-plugin-antfu: ^3.2.3
  test:
    '@types/lodash-es': ^4.17.12
    '@vitest/coverage-v8': ^5.0.3
    '@vitest/ui': ^5.0.3
    lodash-es: ^4.18.1
    vitest: ^5.0.3

  pwa:
    '@vite-pwa/assets-generator': ^2.0.0
    '@vite-pwa/workbox-build': ^8.0.9
    '@vite-pwa/workbox-window': ^8.0.9
    '@vite-pwa/workbox-swkit': ^8.0.9

  inspector:
    '@iconify-json/mdi': ^1.2.3
    '@iconify-json/svg-spinners': ^1.2.4
    '@iconify-json/tabler': ^1.2.41
    '@unocss/reset': ^66.10.5
    '@vitejs/devtools': ^0.7.6
    '@vitejs/devtools-kit': ^0.7.6
    '@vueuse/core': ^14.4.0
    devframe: ^1.2.0
    unocss: ^66.10.5
    vue-router: ^5.3.1

  preact:
    preact: ^10.29.8
  react:
    '@types/react': ^19.3.0
    react: ^19.3.0
  solid-js:
    solid-js: ^1.9.15
  svelte:
    svelte: ^5.57.1
  types:
    '@types/node': 24.19.1
    '@types/trusted-types': ^2.0.7
  typescript:
    typescript: ~6.0.3
  utils:
    '@antfu/ni': ^25.0.0
    '@arethetypeswrong/core': ^0.18.5
    '@playwright/test': 1.63.0
    '@rolldown/pluginutils': ^1.0.1
    '@sentry/vite-plugin': ^5.4.0
    hookable: ^6.1.2
    magic-string: ^1.4.2
    magicast: ^0.5.5
    playwright-core: 1.63.0
    publint: ^0.3.25
    rolldown: ^1.2.12
    taze: 21.1.0
    tinyglobby: ^0.2.17
    typedoc: ^0.28.20
    unrun: ^0.3.1
    verkit: ^0.5.0
    why-is-node-running: 3.2.1

  vite:
    vite: ^8.3.2
  vite5:
    vite: npm:vite@5.3.6
  vite6:
    vite: npm:vite@6.4.3
  vite7:
    vite: npm:vite@7.3.6
  # vite 8
  vite-plugin-inspect:
    '@vitejs/devtools': 0.3.4
    vite-plugin-inspect: 12.0.2
  # vite 6/7
  vite-plugin-inspect-legacy:
    vite-plugin-inspect: npm:vite-plugin-inspect@11.4.1
  vite-plugin-inspect-ancient:
    vite-plugin-inspect: npm:vite-plugin-inspect@0.7.42
  vue:
    '@vitejs/plugin-vue': ^6.0.9
    vue: 3.5.43
    vue-tsc: ^3.3.12

minimumReleaseAgeExclude:
  - vite@8.3.2
  - svelte@5.56.9
  - '@vite-pwa/workbox-build@8.0.9'
  - '@vite-pwa/workbox-swkit@8.0.9'
  - '@vite-pwa/workbox-window@8.0.9'

supportedArchitectures:
  os:
    - win32
    - darwin
    - current
  cpu:
    - x64
    - arm64
